name: Image metadata check CI

on:
  #push:
  #  branches: [master]
  pull_request:
    paths:
      - '**.webp'
      - '**.png'
      - '**.jpg'
  
jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    env:
      SHA: ${{ github.event.pull_request.head.sha }}
      BASE_SHA: ${{ github.event.pull_request.base.sha }}

    steps:
      - name: exiftool installation
        run: |
          sudo apt-get install --assume-yes exiftool

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # this makes the HEAD be the last commit on the PR, not the merge commit, so wrong older commits would get buried
          # ref: ${{ github.event.pull_request.head.sha }}

      - name: read/export image metadata
        run: |
          mapfile -t image_files < <(git diff --name-only ${BASE_SHA} ${SHA} | grep '\.webp$')

          git status

          echo "file is ${image_files[0]}"

          for file in "${image_files[@]}"; do
            echo "file is $file"
            exiftool -Artist -Copyright $file
          done
