name: Image metadata check CI

on:
  #push:
  #  branches: [master]
  pull_request:
    paths:
      - '**.webp'
      - '**.png'
      - '**.jpg'
  
jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    env:
      SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: exiftool installation
        run: |
          sudo apt-get install --assume-yes exiftool

      - name: read/export image metadata
        run: |
          mapfile -t image_files < <(git diff --name-only `git merge-base origin/master HEAD` | grep '\.webp$')
          for file in "${image_files[@]}"; do
            exiftool -Artist -Copyright $file
          done
