name: Image metadata check CI

on:
  push:
    branches: [master]
  pull_request_target:
    paths:
      - **.webp
      # - **.png
      # - **.jpg
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

  steps:
    env:
      SHA: ${{ github.event.pull_request.head.sha }}
    - name: exiftool installation
      run: |
        # not sure if this should be used
        # apt update
        apt-get install --assume-yes exiftool
    - name: read/export image metadata
      run: |
        mapfile -t image_files < <(git diff --name-only HEAD "$SHA" | grep '\.webp$')
        for file in "${image_files[@]}"; do
          exiftool -UserComment $file
        done
